# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/side_sports', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SideSport. As you add validations to SideSport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      SideSport.create! valid_attributes
      get side_sports_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      side_sport = SideSport.create! valid_attributes
      get side_sport_url(side_sport)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_side_sport_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      side_sport = SideSport.create! valid_attributes
      get edit_side_sport_url(side_sport)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new SideSport' do
        expect do
          post side_sports_url, params: { side_sport: valid_attributes }
        end.to change(SideSport, :count).by(1)
      end

      it 'redirects to the created side_sport' do
        post side_sports_url, params: { side_sport: valid_attributes }
        expect(response).to redirect_to(side_sport_url(SideSport.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new SideSport' do
        expect do
          post side_sports_url, params: { side_sport: invalid_attributes }
        end.to change(SideSport, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post side_sports_url, params: { side_sport: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested side_sport' do
        side_sport = SideSport.create! valid_attributes
        patch side_sport_url(side_sport), params: { side_sport: new_attributes }
        side_sport.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the side_sport' do
        side_sport = SideSport.create! valid_attributes
        patch side_sport_url(side_sport), params: { side_sport: new_attributes }
        side_sport.reload
        expect(response).to redirect_to(side_sport_url(side_sport))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        side_sport = SideSport.create! valid_attributes
        patch side_sport_url(side_sport), params: { side_sport: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested side_sport' do
      side_sport = SideSport.create! valid_attributes
      expect do
        delete side_sport_url(side_sport)
      end.to change(SideSport, :count).by(-1)
    end

    it 'redirects to the side_sports list' do
      side_sport = SideSport.create! valid_attributes
      delete side_sport_url(side_sport)
      expect(response).to redirect_to(side_sports_url)
    end
  end
end
