# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/sides', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Side. As you add validations to Side, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Side.create! valid_attributes
      get sides_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      side = Side.create! valid_attributes
      get side_url(side)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_side_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      side = Side.create! valid_attributes
      get edit_side_url(side)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Side' do
        expect do
          post sides_url, params: { side: valid_attributes }
        end.to change(Side, :count).by(1)
      end

      it 'redirects to the created side' do
        post sides_url, params: { side: valid_attributes }
        expect(response).to redirect_to(side_url(Side.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Side' do
        expect do
          post sides_url, params: { side: invalid_attributes }
        end.to change(Side, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sides_url, params: { side: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested side' do
        side = Side.create! valid_attributes
        patch side_url(side), params: { side: new_attributes }
        side.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the side' do
        side = Side.create! valid_attributes
        patch side_url(side), params: { side: new_attributes }
        side.reload
        expect(response).to redirect_to(side_url(side))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        side = Side.create! valid_attributes
        patch side_url(side), params: { side: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested side' do
      side = Side.create! valid_attributes
      expect do
        delete side_url(side)
      end.to change(Side, :count).by(-1)
    end

    it 'redirects to the sides list' do
      side = Side.create! valid_attributes
      delete side_url(side)
      expect(response).to redirect_to(sides_url)
    end
  end
end
